# Generated by Django 3.0.8 on 2021-06-14 01:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=100)),
                ('servicePrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Washer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.CharField(max_length=500)),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageName', models.CharField(max_length=100)),
                ('packagePrice', models.IntegerField()),
                ('serviceName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderLocation', models.CharField(max_length=100)),
                ('orderType', models.CharField(choices=[('Reguler', 'Reguler'), ('Express', 'Express')], max_length=100)),
                ('orderPrice', models.IntegerField()),
                ('orderDate', models.DateField()),
                ('orderTime', models.TimeField()),
                ('customerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.Customer')),
                ('packageName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.Package')),
                ('serviceName', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backendapp.Service')),
                ('washerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.Washer')),
            ],
        ),
    ]
